### PR TITLE
Version checker updates.

### PR DESCRIPTION
**Pull request by mrinc**
Lets check the version from github as webidsupport.com/version.txt isn't maintained anymore.
Unstable option removed as renlok does not keep multiple branches currently.
@renlok - we could use branches to allow different release types (stable/unstable/alpha/beta etc...).
Adding ability to disable the update check

### CODE REVIEW

**Comment by Shaman1977** [comment]
Possible stupid question. Why to check the version here? In my opinion initially was correct. With check actually in the presence of a stable release.

**Comment by mrinc** [comment]
@Shaman1977 WeBid shows the update status on the admin dashboard, so as it times out trying to hit the webidsupport.com page and the dashboard wont load.
On my server, internet access is disabled so it wont ever load the page so I need to have the option to disable update checking.

**Comment by aucsta** [comment]
What about when this is released will the link still be available. The original one works perfect as it tells what version is released fully so really this can be closed

**Comment by mrinc** [comment]
@renlok The link doesn't always work as I have seen, (Today was the first time since I have installed WeBid that I have seen the site actually respond) 
When it is released, the link should still be available until you physically move this repo.  (It is a direct Github link to the file)
The main reason for the merge is "Adding ability to disable the update check"
If you aren't able to load the version.txt (from the site or Github), you can't actually load the admin panel.
So being able to disable it was key.

The nice part using the Github link over a hosted file is you dont have to maintain it or have your CI update it etc... However, if you use the Github link, you mustn't move the repo without preparing.

If you following a branching strategy where develop is your standing branch before a merge to master, then you can set the version checker to check develop for the beta version and you don't have to worry about multiple files etc.

**Comment by renlok** [comment]
Ok I think you're probably right, I just need to sort the repos out having master be the current stable release and then having beta and develop with all pulls being accepted to develop and develop being merge into master and beta as and when.

**Comment by aucsta** [comment]
in my opinion If you were to change it then you would have to alter the webidsupport.com download section. wouldnt changing this make it always be out of date when you decide to work on the next release. people will be getting frustrated because it would be showing an error all the time.

**Comment by aucsta** [comment]
im sure renlok you know what your doing. any ideas on when this version might be released. is there anything you can delegate to others and im happy to help with what I can

**Comment by mrinc** [comment]
@renlok Awesome :) 
Will continue make more merge requests with fixes as I find them.

**Comment by renlok** [comment]
This has been pushed into the dev branch

**Pull request merged**
