### PR TITLE
Add surname

### PR DESCRIPTION
**Pull request by MESWEB**
Added missing surname

### CODE REVIEW

**Comment by renlok** [comment]
Good but some errors
you added two variables names $TPL_name_hidden change the surname one to $TPL_surname_hidden
and two template variables called MISSING0 change one to MISSINGSURNAME or something

**Comment by MESWEB** [comment]
Yes I do it fast without trying it. I make only example for add this to the system.

**Comment by aucsta** [comment]
I've mastered this. you need to add a field in database.
Then need to edit admin/listuser, admin/newuser, edit_data, profile, emails and various other files both php and tpl I'm working on them now and will update at some point today

**Comment by MESWEB** [comment]
THX I will be waiting for it. WeBid support don't want make this - I don't know why?

**Comment by aucsta** [comment]
i think I've completed it just need to wait for it to be accepted if it is then this request can be closed

**Comment by renlok** [comment]
It probably wont be added by default as not just western people use webid
https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/

**Comment by MESWEB** [comment]
WTF??? AYFKM?
You have right - I should send question to ebay and paypal - "Why are You using Surname in ebay or paypal system?" Fantastic idea for thefts - he can create seller account in webid system then he type name and false data, next he sell some things and collect money from customers and when Police comes to You for seller details You give them only fu...ing "Name" like "bhghbhg". 

FACEPALM

**Comment by aucsta** [comment]
never mind mate its fairly easy to do, I'm not a brilliant coder I'm self taught and i figured it out only takes 45 mins to an hour to do. if you want me to ill upload some instructions via rebid support and send you a link.

**Comment by MESWEB** [comment]
Yeah ok. But this is without support!

**Comment by Nozlaf** [comment]
I don't understand why this is such a big deal if it's a single field or not how are you going to stop people providing false information

**Comment by MESWEB** [comment]
@Nozlaf because I want make trust auction system for customers from my country. So if somebody want sell on my site he should activate account like paypal system or ebay - You need prove Your detail information before selling. If someone make fake account with name e.g. "hghjhjgfhj" so how I can find him for back my money?

**Comment by Nozlaf** [comment]
How does the extra field help I could create an account with a fake name using two fields just as easy as one

Also How would you handle someone with two surnames or no surname

**Comment by Nozlaf** [comment]
And ultimately if they are using PayPal for payment it's up to PayPal to authenticate

**Comment by MESWEB** [comment]
First thing I need make trusted portal auction for all customers from my country. If anyone want sell something he should active account by send some amount cash by bank transfer. If details info from website is this same on bank transfer then Admin accept users as seller.

BTW. I don't want use FU...KING PAYPAL because I have ban for all my life and I don't know why. So this is reason why people should don't use paypal shit! Anyway if seller want money for item he can enter his own bank account number for transferring money. So SURNAME need to be added!!!

**Comment by aucsta** [comment]
the is the database 
ALTER  TABLE  `webid_users`  ADD  `surname`TINYTEXTCHARACTER  SETlatin1COLLATElatin1_swedish_ciNULL  AFTER  `name`;

STEP.1
you already have the register files except register.php where is says at the bottom
'MISSING0' => ($missing['surname']) ? 1 : 0,

change to 

'MISSINGS' => ($missing['surname']) ? 1 : 0,

then where is says
'V_YNAME' => (isset($_POST['TPL_surname'])) ? $_POST['TPL_surname'] : '',

change to

'V_SNAME' => (isset($_POST['TPL_surname'])) ? $_POST['TPL_surname'] : '',

STEP.2
and in the register.tpl
change to
<div class="form-group col-lg-6 has-error">
 					<label for="TPL_surname">{L_002a} *</label>
 					<input type="text" class="form-control" name="TPL_surname" id="inputError1" value="{V_SNAME}" autofocus>
 					<div class="error-box missing">{L_937}</div>
 				</div>

STEP3
Language/en/messages.inc.php
$MSG['002'] = "Full name";

Change to

$MSG['002'] = "First name"; 
$MSG['002a'] = "Last name";

**Comment by aucsta** [comment]
STEP.2
and in the register.tpl
change to
<div class="form-group col-lg-6 has-error">
 					<label for="TPL_surname">{L_002a} *</label>
 					<input type="text" class="form-control" name="TPL_surname" id="inputError1" value="{V_SNAME}" autofocus>
 					<div class="error-box missing">{L_937}</div>
 				</div>

STEP3
Language/en/messages.inc.php
$MSG['002'] = "Full name";

Change to

$MSG['002'] = "First name"; 
$MSG['002a'] = "Last name";

**Comment by aucsta** [comment]
STEP.2
and in the register.tpl
change the 3 
MISSING0
TO
MISSINGS

then change 
V_YNAME
to
V_SNAME

STEP3
Language/en/messages.inc.php
$MSG['002'] = "Full name";

Change to

$MSG['002'] = "First name"; 
$MSG['002a'] = "Last name";

**Comment by aucsta** [comment]
STEP4
admin/listusers.php
line 37 change to
'C_NAME' => $USER['name'],
'CS_NAME' => $USER['surname']

line 47 change to
$query = "SELECT id, name, surname, email, balance FROM " . $DBPrefix . "users WHERE id = :user_id";

below line 59 add
'CS_NAME' => $USER['surname'],

line 129 to134 replace with
$keyword = $system->cleanvars($_POST['keyword']);
	$query = "SELECT COUNT(id) as COUNT FROM " . $DBPrefix . "users
			WHERE name LIKE :name OR surname LIKE :surname OR nick LIKE :nick OR email LIKE :email";
	$params[] = array(':name', '%' . $keyword . '%', 'str');
        $params[] = array(':surname', '%' . $keyword . '%', 'str');
	$params[] = array(':nick', '%' . $keyword . '%', 'str');
	$params[] = array(':email', '%' . $keyword . '%', 'str');

line 170 to174 replace with
$keyword = $system->cleanvars($_POST['keyword']);
			WHERE name LIKE :name OR surname LIKE :surname OR nick LIKE :nick OR email LIKE :email";
	$params[] = array(':name', '%' . $keyword . '%', 'str');
        $params[] = array(':surname', '%' . $keyword . '%', 'str');
	$params[] = array(':nick', '%' . $keyword . '%', 'str');
	$params[] = array(':email', '%' . $keyword . '%', 'str');

below 194 add
'SURNAME' => $row['surname'],

**Comment by aucsta** [comment]
Step5
Themes/admintheme/listusers.tpl
line 58 change
<td>{users.NAME}</td>
to
<td>{users.NAME} {users.SURNAME}</td>

**Comment by aucsta** [comment]
STEP6
admin/edituser.php
below line 155 add
surname = :surname,

below line 167 add
$params[] = array(':surname', $system->cleanvars($_POST['surname']), 'str');

below line 238 add
'SURNAME' => $user_data['surname'],

**Comment by aucsta** [comment]
Step7
themes/admintheme/edituser.tpl
below line 15 add
<tr>
						<td width="204">{L_002a} *</td>
						<td><input type="text" name="name" size="40" maxlength="255" value="{SURNAME}"></td>
					</tr>

**Comment by aucsta** [comment]
step 8 
admin/newuser.php
search everything that says name and next to it or below copy and paste the line but this time changing Name to surname

**Comment by aucsta** [comment]
step9 
themes/admintheme/newuser.tpl
repeat step 7

**Comment by aucsta** [comment]
Step 10 
edit_data.php
below line 267 add
'SURNAME' => $USER['surname'],

**Comment by aucsta** [comment]
STEP11
themes/THEME/edit_data.tpl
change line 3 to 
<h3>{NAME} {SURNAME}<i> <span class="text-muted"><small>{NICK}</small></span></i></h3>

**Comment by aucsta** [comment]
STEP 12
includes/emails/user_supended.php
line 22 change
'C_NAME' => $USER['name']
to
'C_NAME' => $USER['name'],
'CS_NAME' => $USER['surname']

then do the same to all the files in this folder that has C_NAME

**Comment by aucsta** [comment]
STEP 13
language/en/emails
locate all files from both folders
and the ones that say C_NAME change to C_NAME CS_NAME

and the ones that say NAME OR REALNAME change to NAME/REALNAME SURNAME

if the say anything else like S_NAME then ignore these files

**Comment by aucsta** [comment]
I hope this helps you out MESWEB if you are stuck on any part then just let me know and I'll do my best to help you.

**Comment by Nozlaf** [comment]
So how do you handle someone who has no surname e.g. a business 
If I try and register on that site as my businesses I can't fill in those fields I want to put. "Nozlaf Family trust pty ltd". Because you changed to firstname and surname I can't register it provides no greater security because I can still enter hfhsjak Djrjekwk. As first name and surname

**Comment by MESWEB** [comment]
@aucsta Thx bro.
@Nozlaf GTFOH! You are idiot! How much peoples have companies? 5% or 7% of country population? So try register Your account on my website - believe me without name and surname I'm reject account like this.

**Pull request closed without merging**
