### PR TITLE
error with last update when trying to install

### PR DESCRIPTION
**Pull request by aucsta**
with the last update of this file by moving this you get a serious database error when trying to install. it needs to stay where it is to work

### CODE REVIEW

**Comment by robberteggermont** [comment]
What is the database error that you get?

The purpose of that change was to enable logging of database errors, so could it be that you are now seeing a problem that was always already there (somewhere else in the code)?

**Comment by aucsta** [comment]
Error with MySQL (my site name).webid_settings """""""" template/databasepdo.php line 215

**Comment by robberteggermont** [comment]
Seems like an error somewhere else in the code. Enable debugging (set 'WeBidDebug' to true in common.php) to obtain the backtrace and see which database query caused this error message.

**Comment by aucsta** [comment]
Ok mate I'll try tomorrow

**Comment by MESWEB** [comment]
This seems like something is wrong with webid_settings table like missing values or bad value of items.

**Comment by aucsta** [comment]
Could someone please look into it as my skills are limited

**Comment by MESWEB** [comment]
So copy and paste here all errors without editing.

**Comment by aucsta** [comment]
Warning: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'aucsta.webid_settings' doesn't exist in /hermes/bosnaweb07a/b1189/ipg.aucstacom/includes/database/DatabasePDO.php on line 215

**Comment by robberteggermont** [comment]
That error seems to indicate a problem in the database settings. Without a backtrace  (see my previous comment) it's impossible to diagnose this.

I just did a fresh install from scratch without any problem. I didn't see this error. Since the problem you have is not related to the change, I suggest you close close this pull request #489 .

**Comment by aucsta** [comment]
so I set webid debug to true and it kept showing this
Notice [8] Undefined variable: system on /hermes/bosnaweb07a/b1189/ipg.aucstacom/includes/functions_admin.php line 115 
Notice [8] Trying to get property of non-object on /hermes/bosnaweb07a/b1189/ipg.aucstacom/includes/functions_admin.php line 115

**Comment by MESWEB** [comment]
What is  Your line 115??
Is this:
```php
 curl_setopt($curl, CURLOPT_REFERER, $system->SETTINGS['siteurl']);
`

**Comment by MESWEB** [comment]
So then what is value of "siteurl" in settings in DB?

**Comment by aucsta** [comment]
this field doesn't exist so that must mean that there is an error with the database system because this is a fresh install

**Comment by robberteggermont** [comment]
> Notice [8] Undefined variable: system on 
> /hermes/bosnaweb07a/b1189/ipg.aucstacom/includes/functions_admin.php 
> line 115

It seems the load_file_from_url function is missing a 'global $system;' 
line. What happens when you insert that at the start of the function?

**Comment by aucsta** [comment]
I have no idea what to do but I also noticed that in admin version check it says the server can't check url whether it's related I'm not sure

**Pull request closed without merging**
