### PR TITLE
User Cp Backlinks

### PR DESCRIPTION
**Pull request by nay27uk**
User Cp Backlinks

as per the thread here

http://www.webidsupport.com/forums/index.php?threads/webid-1-2-user-cp-back-links-in-default-theme.9784/

and bug tracker report here

http://www.webidsupport.com/bugs/view.php?id=566

**IMPORTANT NOTE!!!!!!**
There is also an old commit in there called **Merge remote-tracking branch 'refs/remotes/origin/master' into renlok…'** It was a commit I did some time ago that makes the layout of the your_auctions pages better **PLEASE DELETE THAT COMMIT** as I cant delete it, it just showed up when I reinstalled github desktop on my computer and tried to commit my new changes it added that for some reason and I could not get rid of it.

### CODE REVIEW

**Comment by renlok** [comment]
You dont have to worry about the **Merge remote-tracking branch...** commits they dont have any effect, just mean you have updated your version of the repo with this one.

**Comment by nay27uk** [comment]
OK you can feel free to merge then Renlok

**Comment by nay27uk** [comment]
Just wondering if this has been forgotten about

**Comment by renlok** [comment]
no their are just conflicts so i cannot merge it directly, I have to do it manually and just haven't gotten round to it

**Comment by nay27uk** [comment]
Yeah the conflicts are from the commit 	"Merge remote-tracking branch 'refs/remotes/origin/master' into renlok…" but you said that would not get added anyway in an above comment

**Comment by nay27uk** [comment]
If you can please delete the whole lot so that I can submit them again without a commit I made over 2 months ago being included and one that should not even still be there because I completely removed GitHub Desktop from my PC and then reinstalled it when I made this new commit. 

Lets start from the beginning as this github thing don't seem to work properly. 

I know for a fact that the conflicts are not in my PC or in my GitHub fork because I completely removed GitHub desktop from my computer and cleared the registry and all files off of my computer but when reinstalling GitHub Desktop last week and opening GitHub Desktop it automatically added the old Commit and I could not get rid of it out of GitHub Desktop.

Please delete all my comits that are pending and delete them from the github cache so I can start again.

**Comment by renlok** [comment]
lol its alright it took me ages to learn how it worked. Personally I'm not a fan of the github application i prefer sourcetree (https://www.sourcetreeapp.com/) also what i found useful is when im struggling with conflicts i run from the command line:
`git reset --hard`
`git pull`
it will force delete all changes and revert it back to the most recent commit

**Comment by nay27uk** [comment]
Cheers ren I cant seem to be able to find my github command line app it used to get installed with git desktop but it dont seem to any more. Oh well I will redo the changes either today or tomorrow and re submit them. Thanks for that though pal. It just seems every time I try to make a commit and pull request something goes wrong but I am not one to just give up so bear with me

**Pull request closed without merging**
