### PR TITLE
fix for user menu

### PR DESCRIPTION
**Pull request by aucsta**
with the new debug it displays a blank user menu page. by removing this section it displays perfect.

### CODE REVIEW

**Comment by LOD121** [comment]
Changing this line isn't going to fix that. It will just introduce a bug.
`WHERE b.closed = 1 AND **a.seller = :sellers = 0**";`
You can see that it is performing two comparisons which will produce unintended results, or maybe not work at all since I don't think it is valid SQL.

**Comment by aucsta** [comment]
when I leave it as it is the user menu summary displays a blank page and give this error 
Warning trigger [512] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'a.is_read' in 'where clause' on /hermes/bosnaweb07a/b1189/ipg.aucstacom/includes/database/DatabasePDO.php line 216 

but when I make the change then the page displays fine and the error disappears

**Comment by LOD121** [comment]
It sounds like you want the line to look like this:
`WHERE b.closed = 1 AND a.seller = :sellers";`

Note the lack of ` = 0` in my line here. This would make it valid SQL and would work as intended.

**Comment by aucsta** [comment]
thank for that I've altered it. this edit may need looking into but thats all I could come up with to temporarily fix the issue.

**Comment by aucsta** [comment]
if you were to leave the line as is was then you could make it work by adding a column in the database webid_winners. I added the column is_read in the database and it works as well. would be helpful if someone could look in to this.

**Pull request merged**
